/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: msdk_protobuf.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "msdk_protobuf.pb-c.h"
void   czi_protobuf_info__init
                     (CziProtobufInfo         *message)
{
  static const CziProtobufInfo init_value = CZI_PROTOBUF_INFO__INIT;
  *message = init_value;
}
size_t czi_protobuf_info__get_packed_size
                     (const CziProtobufInfo *message)
{
  assert(message->base.descriptor == &czi_protobuf_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t czi_protobuf_info__pack
                     (const CziProtobufInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &czi_protobuf_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t czi_protobuf_info__pack_to_buffer
                     (const CziProtobufInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &czi_protobuf_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CziProtobufInfo *
       czi_protobuf_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CziProtobufInfo *)
     protobuf_c_message_unpack (&czi_protobuf_info__descriptor,
                                allocator, len, data);
}
void   czi_protobuf_info__free_unpacked
                     (CziProtobufInfo *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &czi_protobuf_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor czi_protobuf_info__field_descriptors[18] =
{
  {
    "activation_timestamp",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CziProtobufInfo, activation_timestamp),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "model",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CziProtobufInfo, model),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sn",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CziProtobufInfo, sn),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "software_version",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CziProtobufInfo, software_version),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hardware_version",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CziProtobufInfo, hardware_version),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "light_code",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CziProtobufInfo, light_code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gimbal_angle",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CziProtobufInfo, gimbal_angle),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "master_volume",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CziProtobufInfo, master_volume),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "background_volume",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CziProtobufInfo, background_volume),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "megaphone_switch",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CziProtobufInfo, megaphone_switch),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "megaphone_model",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CziProtobufInfo, megaphone_model),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "loop_model",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CziProtobufInfo, loop_model),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "isListening",
    13,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CziProtobufInfo, islistening),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "startup_mute",
    14,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CziProtobufInfo, startup_mute),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "loss_action",
    15,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CziProtobufInfo, loss_action),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "breath_light",
    16,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CziProtobufInfo, breath_light),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tts_voice",
    17,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CziProtobufInfo, tts_voice),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tts_speed",
    18,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CziProtobufInfo, tts_speed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned czi_protobuf_info__field_indices_by_name[] = {
  0,   /* field[0] = activation_timestamp */
  8,   /* field[8] = background_volume */
  15,   /* field[15] = breath_light */
  6,   /* field[6] = gimbal_angle */
  4,   /* field[4] = hardware_version */
  12,   /* field[12] = isListening */
  5,   /* field[5] = light_code */
  11,   /* field[11] = loop_model */
  14,   /* field[14] = loss_action */
  7,   /* field[7] = master_volume */
  10,   /* field[10] = megaphone_model */
  9,   /* field[9] = megaphone_switch */
  1,   /* field[1] = model */
  2,   /* field[2] = sn */
  3,   /* field[3] = software_version */
  13,   /* field[13] = startup_mute */
  17,   /* field[17] = tts_speed */
  16,   /* field[16] = tts_voice */
};
static const ProtobufCIntRange czi_protobuf_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 18 }
};
const ProtobufCMessageDescriptor czi_protobuf_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CziProtobufInfo",
  "CziProtobufInfo",
  "CziProtobufInfo",
  "",
  sizeof(CziProtobufInfo),
  18,
  czi_protobuf_info__field_descriptors,
  czi_protobuf_info__field_indices_by_name,
  1,  czi_protobuf_info__number_ranges,
  (ProtobufCMessageInit) czi_protobuf_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
